[package]
name = "db_view"
version = "0.1.0"
edition = "2024"

[features]
default = []
builtin-duckdb = ["db/builtin-duckdb"]

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
tokio.workspace = true
tokio-util.workspace = true
chrono.workspace = true
tracing.workspace = true
futures.workspace = true
smol.workspace = true
gpui.workspace = true
ai_chat_view.workspace = true
db.workspace = true
er_flow.workspace = true
extension-component = { workspace = true }
ferrum-flow.workspace = true
gpui-component = { workspace = true }
one-ui.workspace = true
connection-form.workspace = true
one-core.workspace = true
sum-tree.workspace = true
lsp-types.workspace = true
uuid.workspace = true
rust_xlsxwriter.workspace = true
rust-i18n.workspace = true
json5.workspace = true
regex.workspace = true
parking_lot.workspace = true
once_cell.workspace = true
[dev-dependencies]
gpui = { workspace = true, features = ["test-support"] }
proptest = { workspace = true }
zip = "6.0.0"

[lints]
workspace = true
