[package]
name = "terminal"
version = "0.1.0"
edition = "2021"

[dependencies]
# Async runtime
tokio = { workspace = true }
tokio-util = { workspace = true }
futures = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
one-core = { workspace = true }
gpui = { workspace = true }
ssh = { workspace = true }

# Terminal emulation
alacritty_terminal.workspace = true
serde = { workspace = true }
shell-words = { workspace = true }
tracing = { workspace = true }
serialport = { workspace = true }
base64 = { workspace = true }
dirs = { workspace = true }
polling = "3.11.0"


[target.'cfg(unix)'.dependencies]
libc = "0.2"
