[package]
name = "connection-form"
version = "0.1.0"
publish.workspace = true
edition.workspace = true

[dependencies]
gpui.workspace = true
gpui-component.workspace = true
one-core.workspace = true
rust-i18n.workspace = true

[dev-dependencies]
gpui = { workspace = true, features = ["test-support"] }

[lints]
workspace = true
