[package]
name = "extension_view"
version = "0.1.0"
publish.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
futures = { workspace = true }
gpui = { workspace = true }
gpui-component = { workspace = true }
one-core = { workspace = true }
rust-i18n = { workspace = true }
semver = { workspace = true }

[dev-dependencies]
tempfile = "3"

[lints]
workspace = true
