[package]
name = "redis_view"
version = "0.1.0"
publish.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
agent_runtime.workspace = true
async-trait.workspace = true
base64.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
thiserror.workspace = true
gpui.workspace = true
gpui-component.workspace = true
ai_chat_view.workspace = true
one-ui.workspace = true
connection-form.workspace = true
one-core.workspace = true
rust-i18n.workspace = true
dashmap.workspace = true
futures.workspace = true
redis_client.workspace = true
ssh.workspace = true

[lints]
workspace = true
